services:
  node:
    image: node:${NODE_VERSION}
    command: /bin/sh -c "npm install && tail -f /dev/null"
    restart: no
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app

  mongo:
    image: mongo:${MONGO_VERSION}
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      TZ: ${TZ}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - db_config:/data/configdb:rw
      - db_data:/data/db:rw

  mongoexpress:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "${MONGO_MGMNT_PORT:-8081}:8081"
    depends_on:
      - mongo
    environment:
      TZ: ${TZ}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_OPTIONS_EDITORTHEME: "darcula"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  db_config:
  db_data:
